char* serve_command(char* command_line);
bool user_exists(char* username);
bool group_exists(char* group_id);
char* get_groups();
bool request_exists(char* group_id, char* username);
char* get_requests();
void delete_line(string old_file, string deleteline);
bool is_owner(char* group_id, char* username);
bool is_member(char* group_id, char* username);
int  hash_code(string text);
bool file_exists(char* group_id, char* filename);
void append_file(string file_name, string group_id, int file_size, string file_sha1);
char* get_files_by_group(char* group_id);
pair<char*,int> get_tracker_info(char* tracker_path, int tracker_no);